CREATE TABLE IF NOT EXISTS projects(
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name text NOT NULL CHECK (name <> ''), 
    priority integer NOT NULL,
    description text,
    deliverydate date NOT NULL
);

CREATE TABLE IF NOT EXISTS tasks(
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name text NOT NULL CHECK (name <> ''), 
    done BOOLEAN,
    proyectId INTEGER REFERENCES projects(id)
);

INSERT INTO projects(name, priority, description, deliverydate)
VALUES('Make a Web App', 1, 'Using Javascript', '2022-03-25')

INSERT INTO projects(name, priority, description, deliverydate)
VALUES('Make an App', 1, 'Using Dart', '2022-03-26');

INSERT INTO projects(name, priority, description, deliverydate)
VALUES('Make a Desktop App', 2, 'Using C++', '2022-04-04');


-- INSERT TASKS DATA
INSERT INTO tasks(name, done, proyectId)
    VALUES('donwload Vuejs', false, 1);

INSERT INTO tasks(name, done, proyectId)
    VALUES('Create UI Web', false, 1);

INSERT INTO tasks(name, done, proyectId)
    VALUES('Download Flutter', false, 2);

INSERT INTO tasks(name, done, proyectId)
    VALUES('Design UI', false, 2);